export const GET_LIST_COMBO_SERVICE = "GET_LIST_COMBO_SERVICE"
export const GET_LIST_COMBO_SERVICE_SUCCESS = "GET_LIST_COMBO_SERVICE_SUCCESS"
export const GET_LIST_COMBO_SERVICE_FAIL = "GET_LIST_COMBO_SERVICE_FAIL"

export const ADD_COMBO_SERVICE = "ADD_COMBO_SERVICE"
export const ADD_COMBO_SERVICE_SUCCESS = "ADD_COMBO_SERVICE_SUCCESS"
export const ADD_COMBO_SERVICE_FAIL = "ADD_COMBO_SERVICE_FAIL"