export const GET_LIST_COMBO_SERVICE = "GET_LIST_COMBO_SERVICE"
export const GET_LIST_COMBO_SERVICE_SUCCESS = "GET_LIST_COMBO_SERVICE_SUCCESS"
export const GET_LIST_COMBO_SERVICE_FAIL = "GET_LIST_COMBO_SERVICE_FAIL"