export const GET_LIST_USER = "GET_LIST_USER"
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS"
export const GET_LIST_USER_FAIL = "GET_LIST_USER_FAIL"

export const ADD_USER = "ADD_USER"
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS"
export const ADD_USER_FAIL = "ADD_USER_FAIL"

export const UPDATE_USER = "UPDATE_USER"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_FAIL"